- platform: template
  sensors:
    everyone_home:
      friendly_name: "Everyone Home"
      # delay_on:
      #   minutes: 5
      # delay_off:
      #   minutes: 5
      value_template: >-
        {{ is_state('person.russ_hoffman', 'home')
          and is_state('person.courtney_hoffman', 'home') }}
      icon_template: >-
          {% if is_state("binary_sensor.everyone_home", "on") %}
            mdi:account-supervisor-circle
          {% else %}
            mdi:account-supervisor-circle-outline
          {% endif %}